### ISSUE TITLE
404 for cluster dashboard

### ISSUE THREAD

**Issue by chrisroat** [dask/dask-gateway#261] opened 2020-04-29 06:13 UTC
I setup dask-gateway on a microk8s single-node cluster for testing.  My config is minimal, only setting the gateway.backend.image to my own custom image.   I separately run jupyterhub, with no authentication.  

From a notebook, I can create a cluster and run computations, but: I cannot see the dashboards.

With the cluster object, I get a the following URL:
http://10.64.140.43/clusters/starmap.06630af66e734c3c9463348e2dc36344/status

With the client object, I get:
http://10.64.140.43:8787/status

Going to either the cluster url gives a 404.  Going to the client url times out.

The IP address (also the one I give to the GatewayCluster c'tor) is given by the metallb load balancer, and shows up as the external-ip for traefik-dask-gateway:

```
NAMESPACE            NAME                                                    TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                      AGE
starmap              service/traefik-dask-gateway                            LoadBalancer   10.152.183.38    10.64.140.43   80:31625/TCP                 79m
```

Did I miss a bit of config, either for microk8s or dask-gateway?

**Comment by TomAugspurger** [comment] 2020-04-29 11:43
What version of distributed? There was an issue in 2.15.0 that's fixed in distributed 2.15.1 (released yesterday)

**Comment by chrisroat** [comment] 2020-04-29 16:50
I rebuilt with 2.15.1, but still seem the same behavior.

Here's one thing that I think didn't work before.  If I put the link from the cluster (called Dashboard in the Jupyter UI) in the Dask lab extension, the buttons turn orange.   I believe I tried this previously, but the buttons remained greyed out.

Unfortunately, clicking on any of them opens a tab with a 404 message.  :/

**Comment by scottyhq** [comment] 2020-04-29 16:56
@chrisroat, @TomAugspurger - linking to an issue with the same error using distributed 2.15.1 https://github.com/pangeo-data/pangeo-docker-images/issues/60#issuecomment-621308367. @chrisroat, i'm curious if sticking to distributed <2.15 works for you?

**Comment by chrisroat** [comment] 2020-04-29 17:43
I can rebuild and try it out. Does the tornado version matter? I see I've pinned it to 5.1.1. I recall some conflict with 6.x at one point... though I'm not remembering why at the moment.

**Comment by chrisroat** [comment] 2020-04-29 19:36
Going back to dask 2.14 and distributed 2.14, I am not able to start a cluster.

```
GatewayClusterError: Cluster 'starmap.9f42f7c342c74afbb1cd7f600fcd91fd' failed to start, see logs for more information
```

Logs in traefik-dask-gateway:
```
time="2020-04-29T19:23:57Z" level=error msg="subset not found for starmap/api-dask-gateway" namespace=starmap providerName=kubernetescrd ingress=api-dask-gateway
```

**Comment by consideRatio** [comment] 2020-04-29 21:30
I struggled a bit to configure all the gateway URLs properly in 0.7.1, and this is what I ended up with working on a GKE cluster. https://github.com/pangeo-data/pangeo-cloud-federation/issues/584#issuecomment-621471832

**Comment by chrisroat** [comment] 2020-04-29 22:51
OK.  Some combination of things, including some taken from that comment, have got things working. (except a cluster.shutdown() fails...)  I'll try and figure out the minimal set of things I need.

I had backtracked to dask and distributed 2.14.  @consideRatio Is your setup on 2.14 or 2.15 or 2.15.1?

**Comment by consideRatio** [comment] 2020-04-29 22:59
@chrisroat I have not pinned dask, so probably the latest or 1-2 weeks old version.

**Comment by chrisroat** [comment] 2020-04-30 04:44
In the end, it was a combination of both suggestions on this thread:

1. The idea of @scottyhq of going back to distributed==2.14.0 (which, via conda deps, also meant dask==2.14.0).
2. The recipe of @consideRatio to set a url for the hub dask-gateway service, plus set the gateway address and public-address.

Appreciate the pointers.

**Comment by mrocklin** [comment] 2020-04-30 05:11
If you were using prefixes then there was a bug in 2.15.0.  I recommend
upgrading to 2.15.1 which was released a day or so ago.

**Comment by TomAugspurger** [comment] 2020-04-30 14:25
@mrocklin @jrbourbeau I haven't followed the changes to distributed closely, but does dask-gateway need to pass the `prefix` to the Scheduler it creates at https://github.com/dask/dask-gateway/blob/a2a6b829d31b068008c396ef620f6b87dfb93f47/dask-gateway/dask_gateway/dask_cli.py#L543-L549?

Still figuring this out...

**Comment by jcrist** [comment] 2020-04-30 14:28
Apologies, I don't have time to delve into this deeper right now, just want to stop people from going down an errant path. 

> I haven't followed the changes to distributed closely, but does dask-gateway need to pass the prefix to the Scheduler it creates at 

Regardless of if `dask-gateway-server` is running with a prefix (say installed behind JupyterHub's proxy), we keep the dask dashboards at the default `/` - handing the prefix is done by the traefik proxy before traffic reaches the dashboard.

**Comment by mrocklin** [comment] 2020-04-30 14:31
I didn't mean to point people down a prefix route, merely to say that users
who were using the prefix= flag saw 404's in 2.15.0, and we fixed this in
2.15.1.  If dask-gateway isn't using the prefix= keyword then you can
safely ignore my comment and the issue is likely somewhere else.

**Comment by TomAugspurger** [comment] 2020-04-30 14:32
Thanks Jim, that was my thought too. Just not sure how else this would have changed between 2.14 and 2.15.

I'll try to add some more logging to the scheduler dashboard startup to see what's going on.

**Comment by jcrist** [comment] 2020-04-30 14:35
You might also try pulling out the bits of `dask_gateway.dask_cli` that stand up a scheduler (drop our plugin and services) and see if the dashboard is reachable. Since we don't currently use the existing dask-scheduler cli (could be changed in the future with a preload, just not time right now) how the dashboard service is added and started on the scheduler may have changed? I haven't looked at the changelog for 2.15, not sure.

**Comment by TomAugspurger** [comment] 2020-04-30 18:47
I'm able to reproduce the 404 locally with just

```bash
$ dask-gateway-server
```

and

```
>>> from dask_gateway import Gateway
>>> gateway = Gateway("http://127.0.0.1:8000")
>>> cluster = gateway.new_cluster()
```

and visit the dashboard URL. No jupyterhub needed.

I have to set this aside for a bit. Will come back to it later.

**Comment by TomAugspurger** [comment] 2020-04-30 19:23
Well that was one of the more frustrating debugging sessions :)

```diff
diff --git a/distributed/scheduler.py b/distributed/scheduler.py
index 33bd6373..2887abec 100644
--- a/distributed/scheduler.py
+++ b/distributed/scheduler.py
@@ -1133,7 +1133,7 @@ class Scheduler(ServerNode):
         )
         self.start_http_server(routes, dashboard_address, default_port=8787)
 
-        if dashboard:
+        if dashboard or dashboard_address:
             try:
                 import distributed.dashboard.scheduler
             except ImportError:
```

Not sure why I didn't think to compare the args of `dask-scheduler` and `dask-gateway-scheduler` earlier. Going to make sure that's an appropriate fix for distributed, and will look into whether dask-gateway needs to change at all.

**Comment by mrocklin** [comment] 2020-05-01 01:54
My apologies for the churn here Tom.  Thank you for resolving my mess here.

**Comment by TomAugspurger** [comment] 2020-05-01 14:14
> My apologies for the churn here Tom.  Thank you for resolving my mess here.

No worries, It's just a one line fix :)

We'll release distributed 2.15.2 later today with the fix, which will kick off builds on conda-forge, `pangeo-notebook` conda metapackages, and eventually the pangeo docker images.

So the bad versions will be

- distributed 2.15.0 and 2.15.1
- pangeo-dask 2020.04.25, 2020.04.28
- pangeo-notebook 2020.04.28, 2020.04.28, 2020.04.29
- pangeo/base-notebook  2020.04.27, 2020.04.28, 1391655

**Closed** 2020-05-01 14:47 UTC
