### ISSUE TITLE
Support for K8s v1.22

### ISSUE THREAD

**Issue by chrisroat** [dask/dask-gateway#469] opened 2021-12-13 21:38 UTC
**What happened**:

I needed to upgrade my K8s cluster to v1.22 in order to pick up fixes for issues related to graceful handling of pre-emptible node terminations.  This has some knock-on effects related to ingresses due to some api changes in v1.22.  Specifically in dask-gateway, I see the following in the my `traefik-daskhub-dask-gateway` pods, as the ingress api changed and moved out of beta:

```
Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)"
```

**What you expected to happen**:

I expected some issues.  :)

**Anything else we need to know?**:

I tried simply updating to traefik 2.5, but then run into additional problems.  I see that #431 addresses this, but it looks like it is unreleased and there are a lot of other changes in the repo since the 0.9.0 release I'm using.  

I am not sure how to proceed.  Is there any easy way for me to use v1.22?  Tagging @consideRatio from #431.

**Environment**:

- Dask version: 2021.12.0
- Python version: 3.8
- Operating System: Ubuntu 20
- Install method (conda, pip, source): pip

**Comment by chrisroat** [comment] 2021-12-13 22:32
Appreciate the quick response.  And apologies for not really understanding how dask-gateway works under the hood.

If I move my cluster off a release channel and turn off auto-upgrade, I can maintain some version skew and put the dask-gateway pods on a node pool w/ 1.21.   Would my dask worker node pools also need to be on 1.21?

The pods I so far need on 1.22 are on a separate node pool altogether, unrelated to dask.   

[There is a small chance that my dask workers will need to move to 1.22 if they hit the autoscaler issue.  Hence my question above.]

**Comment by consideRatio** [comment] 2021-12-13 23:09
I think you will have a failure no matter what you do if you have a k8s api-server that is k8s 1.22 and use dask-gateway 0.9.0, because the k8s resources they define have been removed in k8s 1.22 in favor of non-deprecated k8s resource version - i think.

No option but either do a significant manual intervention, or await a new release of dask-gateway (and daskhub helm chart that includes the new dask-gateway version) before upgrading to k8s 1.22.

**Comment by chrisroat** [comment] 2021-12-13 23:12
Understood.  I am experimenting with moving the node pool for the dask-gateway pods (and traefik/schedulers/jupyterhub and other non-worker pods) to 1.21.

The question is then whether the dask workers/scheduler communication would somehow rely on the removed resources (in particular, ingress has been the big one), and if workers can be on 1.22 pods and dask-gateway/traefik/etc on 1.21.

**Comment by chrisroat** [comment] 2021-12-13 23:49
Oh, I see -- the k8s api-server needs to be on 1.21... you weren't talking about the gateway api.  Ouch, this is not going to be fun to roll back.

**Comment by martindurant** [comment] 2022-02-14 18:19
Looking at this now. We have a number of pre-release API blocks, typically "v1alpha1" (all treafik-related) that I think can all go to v1. The issue is, this will leave older kube behind, right? Is there any way to have both - I don't know when these APIs became officially released. Our internal daskcluster CRD I expect can have any version it likes.

**Comment by consideRatio** [comment] 2022-02-14 19:27
> We have a number of pre-release API blocks, typically "v1alpha1" (all treafik-related) that I think can all go to v1.

@martindurant is this what you refer to?

https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/resources/helm/dask-gateway/templates/traefik/dashboard.yaml#L2-L3

https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/resources/helm/dask-gateway/templates/gateway/middleware.yaml#L1-L2

https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/resources/helm/dask-gateway/templates/gateway/middleware.yaml#L13-L14

https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/resources/helm/dask-gateway/templates/gateway/ingressroute.yaml#L1-L2

The resources we define be should match the latest versions of the resource-kind that we have defined in the CRD resources we also provide - which are actually still v1alpha1.

https://github.com/dask/dask-gateway/blob/bee9255e5ea0d77f456985cd91b2622bb3776dbb/resources/helm/dask-gateway/crds/traefik.yaml#L6-L22

There actually are no more modern version of the Traefik resource kinds provided besides v1alpha1: https://github.com/traefik/traefik-helm-chart/blob/HEAD/traefik/crds/ingressroute.yaml#L17

**Comment by martindurant** [comment] 2022-02-14 19:40
Sounds good!

**Comment by consideRatio** [comment] 2022-02-16 00:47
Okay I'm quite confident this is resolved by bumping the version of traefik, and that we should be good to go on k8s 1.22.

**Closed by consideRatio** 2022-02-16 00:47 UTC
